llm:
  provider: openai       # Supported: openai, aws_bedrock, anthropic, gemini
  model: gpt-4           # e.g. gpt-4, gpt-3.5-turbo
  temperature: 0.0
  max_tokens: 64
  api_key_env: OPENAI_API_KEY

tasks:
  sentiment:
    type: binary
    prompt_template: "Classify the sentiment of the following movie review as Positive or Negative:\n\n"
  product_category:
    type: multiclass
    classes:
      - Electronics
      - Books
      - Clothing
      - Home
    prompt_template: "Assign one of the following categories to this review: {{ classes }}:\n\n"

server:
  host: 0.0.0.0
  port: 8000