version: '3.8'
services:
  llm-classifier:
    build: .
    container_name: llm-classifier
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped